apiVersion: v1
kind: Namespase
metadata:
  name: user-service-namespase

---

apiVersion: v1
kind: Service
metadata:
  name: user-service-app
  namespase: user-service-namespase
spec:
  type: LoadBalancer
  selector:
    app:  user-service-pod
  ports:
    - protocol: "TCP"
      port: 8083
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
  namespase: user-service-namespase
spec:
  selector:
    matchLabels:
      app: user-service-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: user-service-pod
        owner: userservicegroup
    spec:
      containers:
        - name: user-service
          - image: kazimirshklennikdev/user-service:latest
            ports:
              - containerPort: 8080


