spring:
  application:
    name: user-service

  http:
    log-request-details: true
    encoding:
      charset: UTF-8

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost/user-service-db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

logging:
  level:
    org:
      springframework: ERROR
    com:
      mkyong: ERROR
      root: ERROR