# Default values for user-posts-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace:
  name: posts-namespace2

settings:
  javaOpts: -Xms500m -Xmx500m
  app:
    userApp:
      database:
        userDbHost: jdbc:postgresql://user-db-svc:5432/user-db
        userDbUserName: userServiceUser
        userInitDbFile: file:/usr/share/userservice/schema.sql
    topicApp:
      database:
        topicDbHost: jdbc:postgresql://topic-db-svc:5432/user-post-db
        topicDbUserName: topicServiceUser