# Default values for user-posts-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

topic-app:
  replicaCount: 1
  namespace:
    name: posts-namespace
  app:
    javaOpts: -Xms500m -Xmx500m
    database:
      topicDbHost: jdbc:postgresql://topic-db-svc:5432/user-post-db
      topicDbUserName: topicServiceUser

user-app:
  replicaCount: 1
  namespace:
    name: posts-namespace
  app:
    javaOpts: -Xms500m -Xmx500m
    database:
      userDbHost: jdbc:postgresql://user-db-svc:5432/user-db
      userDbUserName: userServiceUser
      userInitDbFile: file:/usr/share/userservice/schema.sql
