apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: posts-namespace
  name: topic-app
spec:
  selector:
    matchLabels:
      app: topic-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: topic-app
    spec:
      containers:
        - name: topic-app
          image: kazimirshklennikdev/topic-service:1.2-release
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: topicDbHost

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: topicDbUserName

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: topicDbPassword

            - name: USER_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: topicUserServiceHost

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            timeoutSeconds: 1
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
              httpHeaders:
                - name: X-Client-Identity
                  value: Kubernetes-Startup-Probe
---

apiVersion: v1
kind: Service
metadata:
  namespace: posts-namespace
  name: topic-app-svc
spec:
  selector:
    app: topic-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort