apiVersion: v1
kind: ConfigMap
metadata:
  namespace: posts-namespace
  name: db-config
data:
  userDbName: user-db
  userDbUserName: userServiceUser
  topicDbUserName: topicServiceUser
  topicDbName: user-post-db