# Default values for topic-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace:
  name: posts-namespace

image:
  repository: kazimirshklennikdev/topic-service
  pullPolicy: IfNotPresent
  tag: "1.2-release"
  containerPort: 8080

imagePullSecret:
  enabled: true

livenessProbe:
  # -- On/Off toggle for a probe which detects that application still alive
  enabled: true
  # -- How many time probe has to be failed before k8s terminate a pod
  failureThreshold: 3
  # -- Delay before the first probe will be do after pod start
  initialDelaySeconds: 30
  # -- Delay between probes
  periodSeconds: 5

readinessProbe:
  # -- On/Off toggle for a probe which detects that application is ready to serve requests
  enabled: true
  # -- How many time probe has to be failed before k8s stops send requests
  failureThreshold: 3
  # -- Delay before the first probe will be do after pod start
  initialDelaySeconds: 30
  # -- Delay between probes
  periodSeconds: 5

service:
  type: NodePort
  port: 80

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

settings:
  javaOpts: -Xms500m -Xmx500m
  app:
    topicApp:
      topicUserServiceHost: http://posts-user-app:8080
      database:
        topicDbHost: jdbc:postgresql://topic-db-svc:5432/user-post-db
        topicDbUserName: topicServiceUser