spring:
  application:
    name: user-post-service

  http:
    log-request-details: true
    encoding:
      charset: UTF-8

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost/user-post-db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

management:
  monitoring:
    enabled: ${APPLICATION_MONITORING:true}
  health:
    mail:
      enabled: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
    env:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: metrics,info,health,env,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

services:
  host:
    user: ${USER_SERVER_HOST:http://localhost:8080}

logging:
  level:
    org:
      springframework: ERROR
    com:
      mkyong: ERROR
      root: ERROR