# Default values for user-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: kazimirshklennikdev/user-app
  pullPolicy: IfNotPresent
  tag: "1.5-release"
  containerPort: 8080

imagePullSecret:
  enabled: true

livenessProbe:
  # -- On/Off toggle for a probe which detects that application still alive
  enabled: true
  # -- How many time probe has to be failed before k8s terminate a pod
  failureThreshold: 3
  # -- Delay before the first probe will be do after pod start
  initialDelaySeconds: 30
  # -- Delay between probes
  periodSeconds: 5

service:
  type: NodePort
  port: 80

resources: {}
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

settings:
  javaOpts: -Xms500m -Xmx500m
  app:
    database:
      userDbHost: jdbc:postgresql://user-db-svc:5432/user-db
      userDbUserName: userServiceUser
      userDbPassword: cm9vdA==
      userInitDbFile: file:/usr/share/userservice/schema.sql