apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: user-service-namespace
  name: user-service-app-deployment
spec:
  selector:
    matchLabels:
      app: user-service-app
  replicas: 2
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
        - name: user-service-app
          image: kazimirshklennikdev/user-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  host

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  username

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : postgres-secrets
                  key :  password

---

apiVersion: v1
kind: Service
metadata:
  namespace: user-service-namespace
  name: user-service-app-svc
spec:
  selector:
    app: user-service-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort