apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: posts-namespace
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api/v1/user-service/users
            backend:
              service:
                name: posts-user-app
                port:
                  number: 8080
          - path: /api/v1/post-service/posts
            backend:
              service:
                name: posts-topic-app
                port:
                  number: 8080