# Default values for user-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace:
  name: posts-namespace

replicaCount: 1

image:
  repository: kazimirshklennikdev/user-service
  pullPolicy: IfNotPresent
  tag: "1.5-release"
  containerPort: 8080

imagePullSecret:
  enabled: true

livenessProbe:
  # -- On/Off toggle for a probe which detects that application still alive
  enabled: true
  # -- How many time probe has to be failed before k8s terminate a pod
  failureThreshold: 3
  # -- Delay before the first probe will be do after pod start
  initialDelaySeconds: 30
  # -- Delay between probes
  periodSeconds: 5

readinessProbe:
  # -- On/Off toggle for a probe which detects that application is ready to serve requests
  enabled: true
  # -- How many time probe has to be failed before k8s stops send requests
  failureThreshold: 3
  # -- Delay before the first probe will be do after pod start
  initialDelaySeconds: 30
  # -- Delay between probes
  periodSeconds: 5

service:
  type: ClusterIP
  port: 8080

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

settings:
  javaOpts: -Xms500m -Xmx500m
  app:
    userApp:
      database:
        userDbHost: jdbc:postgresql://user-db-svc:5432/user-db
        userDbUserName: userServiceUser
        userInitDbFile: file:/usr/share/userservice/schema.sql